### ISSUE TITLE
Unhandled exception with any older .osz file

### ISSUE THREAD

**Issue by bferguson3** [octoberU/AudicaConverter#3]
Forgive me because I am unfamiliar with osu!.

1. Download song pack 1 from osu! website (very first one from page 64)
2. Drag and drop any osz file onto AudicaConverter.exe
3. Observe error:
`Unhandled exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 at OsuTypes...`

This happens with any of the files, or groups of files. 

Files from the newest osu! pack work, but only if I do them one at a time. 

It also seems like there's something wrong with the input handler, I have to jam the number/enter keys a couple times to get them to work.

**Comment by Zernys** [comment]
Thank you for the report!

Seems there are were some formatting differences for the very first ~100 osu! maps that we didn't handle correctly. **Fixed**.

> Files from the newest osu! pack work, but only if I do them one at a time.

What happens if you drag multiple files or a folder of .osz files onto the converter? Any error messages? Make sure that the folder you're trying to convert is uncompressed, and not in the default .7z format of the osu! betmap packs.

> It also seems like there's something wrong with the input handler, I have to jam the number/enter keys a couple times to get them to work.

That's strange. It should be a standard command prompt, and not something we have implemented ourselves.  I'm not sure how to go about addressing or even replicating that, unless you've noticed some tendency  with when it happens.

**Comment by Zernys** [comment]
Main issue resolved, additional issues assumed as unreplicable. Closed.
